#!/bin/bash -
#
# Obsidian Calendar seeder

cd ~/notes/diary/ || exit
iso_date() {
    # taken from https://unix.stackexchange.com/a/662783
    # input: GGGG-VV-u
    # output: YYYY-mm
    declare -a given
    declare -a calib
    IFS='-' read -r -a given <<<"${1}"
    IFS='-' read -r -a calib <<<"$( LANG=C date -d "${given[0]}-06-01" +'%G-%V-%u' )"
    given[1]=${given[1]#0}
    calib[1]=${calib[1]#0}
    declare offset=$(( 7*(given[1] - calib[1]) + given[2] - calib[2] ))
    LANG=C date -d "${given[0]}-06-01 + ${offset} days" +'m%Y-%m'
}

get_parents() {
    # input: date specification not matching ^\./ or \.md$
    #  meaning it is just the date
    # output: space separated parents, without the trailing ".md"
    #  for all but the weeks, this will be one parent, for a week it could be one or two
    local file=$1
    if [[ $file =~ ^w ]]; then
        # handle week
        # $file is of form wGGGG-VV
        file=${file#w}
        month_a=$(iso_date "${file}-1")
        month_b=$(iso_date "${file}-7")
        [[ $month_a == "$month_b" ]] && echo "$month_a" || echo "$month_a" "$month_b"
        return 0
    fi
    if [[ $file =~ ^m ]]; then
        # handle month
        # $file is of form mYYYY-mm
        LANG=C date -d "${file#m}-01" +'q%Y-%q'
        return 0
    fi
    if [[ $file =~ ^q ]]; then
        # handle quarter
        # $file is of form qYYYY-q
        # simply return the YYYY part
        file=${file#q}
        file=${file%-*}
        echo "$file"
        return 0
    fi
    # handled week, month, quarter
    # left is day and year
    if [[ $file =~ ^[0-9]{4}$ ]]; then
        # years don't get a parent
        return 1
    fi
    # days get the week
    LANG=C date -d "$file" +'w%G-%V'
    return 0
}

# this will be populated with
#    shorter:longer
# pairs. The "longer" files will then later be updated to contain
# the links for the existing "shorter" periods it contains.
#  (eg a week links to the days it contains).
#
# The 'known' array contains files
# already linked to by their parent
declare -A links
declare -A known
known_files="${HOME}/.local/share/mutables/obsidian-diary-index"
[[ -f "$known_files" ]] && {
    while read -r file || [[ -n "$file" ]]; do
        known[$file]=1
    done < "$known_files"
}
set_links_for() {
    local p
    local key
    local file=$1
    [[ -z "${known[$file]}" ]] && {
        known[$file]=1
        echo "$file" >> "$known_files"
    }
    local parents
    if parents=$(get_parents "$file"); then
        # not a year
        for p in $parents; do
            # if link is already set, all parents will already be set
            key=$file:$p
            if [[ -z ${links[$key]} ]]; then
                links[$key]=1
                set_links_for "$p"
            fi
        done
    fi
}

# global array and data for checking if a file has the correct form
declare -A corrected
correct_file () {
    [[ -n ${corrected[$1]} ]] && return 0
    corrected[$1]=1
    [[ $1 =~ ^[0-9]{4}-..-.. ]] && return 0
    if [[ -f $1.md ]] && rg -q '^# Associated Diary Entries$' "$1.md"; then
        # file is ok
        :
    else
        cat >> "$1".md << HERE
# Associated Diary Entries

---

HERE
    fi
}

declare -A changed
update_link () {
    # just paste [[shorter]] into longer.md and ensure
    # that both have correct form
    local shorter=${1%:*}
    local longer=${1#*:}
    correct_file "$shorter"
    correct_file "$longer"
    changed[$longer]=1
    echo "[[$shorter]]" >> "$longer.md"
}

# calculate the links for the files in the diary structure
while read -r file || [[ -n $file ]]; do
    file=${file#./}
    file=${file%.md}
    # if a file is known, all its parents will exist
    # and have the correct entries
    # skip it
    [[ -n "${known[$file]}" ]] && continue
    set_links_for "$file"
done < <( fd -e md '^.?\d{4}' )

# make the files match the links
for item in "${!links[@]}"; do
    update_link $item
done

# now that the links are updated
# some files might link to another file multiple times
# or have the links in the wrong order
#
# use kakoune to fix it
for file in $(fd '^[wmq]' ; fd '\d{4}.md'); do
    key=${file#./}
    key=${key%.md}
    [[ -z "${changed[$key]}" ]] && continue
    # kak -f <keys> runs <keys>	after selecting the whole text.
    # 'ge'
    #    goto last character (linebreak in last line)
    # '<a-?>^---$<ret>
    #    select back to the last line matching '---'
    # '<a-s><a-K><ret><a-_>'
    #    deselect this '---' line
    # '|sort -u<ret>'
    #    filter the remaining text through `sort -u`
    #    which orders the links in the correct way
    #    and drops multiple entries
    kak -n -q -f 'ge<a-?>^---$<ret><a-s><a-K><ret><a-_>|sort -u<ret>' "$file"
done

# copy the diary to the backup directory
rsync -a --delete --exclude='.git/' "${HOME}/notes/diary/" "${HOME}/notes-bak/diary"
sync
cd ~/notes-bak/diary/ || exit

# prepare an incremental diff
# to show to the user
git add -N .
diff_file="${HOME}/notes/diary_diff.md"
{
    echo -n "Latest backup: "
    git log -1 --pretty=%s
    echo '```diff'
    git diff
    echo '```'
} > "$diff_file"

# increment the repository to the newest state
git add .
git commit -m "$(LANG=de_DE.utf8 date +'%Y - %A %d. %B %R %Z')"

# show to the user
# information loss since the last backup will become obvious
obsidian-cli open diary_diff
